### ISSUE TITLE
Using the provided materials create BeamEnergy device class based on the facadedevice library.

### ISSUE THREAD

**Issue by wkitka** [synchrotron-solaris/dev-solaris-beamenergy#1]
Properties:
- [x]  MagnetPSName - A proper Tango name of a power supply which energy is used in calculations.
- [x]  MagnetPSAttribute - Name of the attribute of the PS that the energy will be calculated from.
- [x]  a - The square factor in the energy calculation.
- [x]  b - The linear factor in the energy calculation.
- [x]  c - The absolute factor in the energy calculation.

Attributes:
- [x]  Energy:
	val - value of MagnetPSAttribute
	energy = a * val^2 + b * val + c

**Comment by stanislaw47** [comment]
@LJBD 
I've commited documentation created via `apidoc` but it looks a little strange. Do you have a moment to take a look at this?
